default: &default
  database: backendTest
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 'password'
  host: localhost

development:
  <<: *default
  username: paulo
  password: 'admin'