default: &default
  database: backendTest
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db

development:
  <<: *default

test:
  <<: *default
  username: paulo
  password: 'admin'
  host: localhost